<?php
pll_register_string("Add activity", "Add activity");
pll_register_string("What are you looking for?", "What are you looking for?");
pll_register_string("Link to homepage", "Link to homepage");
pll_register_string("Site logotype", "Site logotype");
pll_register_string("Open search", "Open search");
pll_register_string("Search", "Search");
pll_register_string("Or surf to the promoted categories", "Or surf to the promoted categories");
pll_register_string("Arrow", "Arrow");
pll_register_string("Banner title 1", "Banner title 1");
pll_register_string("Banner title 2", "Banner title 2");
pll_register_string("Activities main title", "Activities main title");
pll_register_string("Activities main subtitle", "Activities main subtitle");
pll_register_string("kids", "kids");
pll_register_string("Order now", "Order now");
pll_register_string("Categories main title", "Categories main title");
pll_register_string("Read more", "Read more");
pll_register_string("Services main title", "Services main title");
pll_register_string("Blog main title", "Blog main title");
pll_register_string("Phone", "Phone");
pll_register_string("Rate and write review", "Rate and write review");
pll_register_string("Footer link", "Footer link");
pll_register_string("All rights reserved 2017 &copy", "All rights reserved 2017 &copy");
pll_register_string("Your review", "Your review");
pll_register_string("Tell us about your experience", "Tell us about your experience");
pll_register_string("Your rating", "Your rating");
pll_register_string("Review title", "Review title");
pll_register_string("Review name", "Review name");
pll_register_string("Review title placeholder", "Review title placeholder");
pll_register_string("Review name", "Review name");
pll_register_string("Review name placeholder", "Review name placeholder");
pll_register_string("Review email", "Review email");
pll_register_string("Review email placeholder", "Review email placeholder");
pll_register_string("Review submit", "Review submit");
pll_register_string("Activity order", "Activity order");
pll_register_string("Adult price", "Adult price");
pll_register_string("Child price", "Child price");
pll_register_string("Order now", "Order now");
pll_register_string("Order as present", "Order as present");
pll_register_string("Get directions", "Get directions");
pll_register_string("To the attraction", "To the attraction");
pll_register_string("Photo gallery", "Photo gallery");
pll_register_string("All photos", "All photos");
pll_register_string("View all images from gallery", "View all images from gallery");
pll_register_string("Next activity", "Next activity");
pll_register_string("Previous activity", "Previous activity");
pll_register_string("Reviews", "Reviews");
pll_register_string("Our Activities", "Our Activities");
pll_register_string("Come and find out", "Come and find out");
pll_register_string("OUR BLOG", "OUR BLOG");
pll_register_string("Our blog subtitle", "Our blog subtitle");
pll_register_string("Phone", "Phone");
pll_register_string("Add your activity", "Add your activity");
pll_register_string("Activity map title", "Activity map title");
pll_register_string("Attraction map title", "Attraction map title");
pll_register_string("Categories main subtitle", "Categories main subtitle");
pll_register_string("Services main subtitle", "Services main subtitle");
pll_register_string("Blog main subtitle", "Blog main subtitle");
pll_register_string("up to", "up to");
pll_register_string("NIS", "NIS");
pll_register_string("Any region", "Any region");
pll_register_string("Any price", "Any price");
pll_register_string("Any tag", "Any tag");
pll_register_string("Any category", "Any category");
pll_register_string("FREE", "FREE");
pll_register_string("Register", "Register");
pll_register_string("Sign In", "Sign In");
pll_register_string("Log In", "Log In");
pll_register_string("Order modal title", "Order modal title");
pll_register_string("Credit text", "Credit text");
pll_register_string("404 title", "404 title");
pll_register_string("404 subtitle", "404 subtitle");
pll_register_string("You must be a registered user to add activity", "You must be a registered user to add activity");
pll_register_string("First need add your attraction", "First need add your attraction");
pll_register_string("over", "over");
pll_register_string("Our Partners", "Our Partners");
pll_register_string("Preview", "Preview");
pll_register_string("Very bad", "Very bad");
pll_register_string("Bad", "Bad");
pll_register_string("Normal", "Normal");
pll_register_string("Good", "Good");
pll_register_string("Very good", "Very good");
pll_register_string("Recommendations", "Recommendations");
pll_register_string("Favourites", "Favourites");
pll_register_string("Search submit", "Search submit");
pll_register_string("Search title", "Search title");
pll_register_string("Search input", "Search input");
pll_register_string("Order now search", "Order now search");
pll_register_string("You are currently logged in as", "You are currently logged in as");
pll_register_string("Log out?", "Log out?");
pll_register_string("Username", "Username");
pll_register_string("Password", "Password");
pll_register_string("Remember Me", "Remember Me");
pll_register_string("Login", "Login");
pll_register_string("Website", "Website");
pll_register_string("Your account is now active!", "Your account is now active!");
pll_register_string("You can", "You can");
pll_register_string("with details:", "with details:");
pll_register_string("Holiday title", "Holiday title");
pll_register_string("Holiday link", "Holiday link");

